config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tickets#index"
  resources :tickets
end

app/models/ticket.rb
# app/models/ticket.rb
class Ticket < ActiveRecord::Base

  #before_initialize :set_default

  DEPARTMENT_SALES      = "sales".freeze
  DEPARTMENT_MARKETING      = "marketing".freeze
  DEPARTMENT_TECHNICAL      = "technical".freeze

  DEPARTMENTS = [ DEPARTMENT_SALES,
      DEPARTMENT_MARKETING,
      DEPARTMENT_TECHNICAL ]

  private

  def set_default
    self.response |= false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @ticket = Ticket.all
  end

   def new
    @ticket = Ticket.new
  end

  # def create
  #   @ticket = Ticket.new(params.require(:ticket).permit([:title, :body]))
  #   if @ticket.save
  #     redirect_to @ticket
  #   else
  #     render :new
  #   end
  # end

    def create
    @ticket = Ticket.new(params.require(:ticket).permit([:email, :name, :title, :body, :resolved]))
    if @ticket.save
      redirect_to tickets_path, notice: "Support Request Saved"
    else
      render :new
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  # def update
  #   @ticket = Ticket.find(params[:id])
  #   if @ticket.update_attributes(params.require(:ticket).permit([:email, :name, :title, :body, :resolved]))
  #     redirect_to @ticket
  #   else
  #     render :edit
  #   end
  # end

  def update
    @ticket = Ticket.find(params[:id])
    if @ticket.update_attributes(params.require(:ticket).permit([:email, :name, :title, :body, :resolved]))
      redirect_to tickets_path
    else
      render :edit
    end
  end



  def destroy
  @ticket = Ticket.find(params[:id])
  @ticket.destroy

  redirect_to tickets_path
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="application.js" type="text/javascript" charset="utf-8"></script>

  <%= csrf_meta_tags %>
</head>
<body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/tickets/edit.html.erb
<!-- app/views/posts/edit.html.erb -->
<h1>Edit Ticket</h1>
<%= form_for @ticket do |f| %>
  <%= f.text_field :title %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>

app/views/tickets/index.html.erb
<h1>All Tickets</h1>

<%= link_to "New Ticket", new_ticket_path, class: "btn btn-default new-ticket"  %>

<% @ticket.each do |ticket| %>
  <h2><%= ticket.title %>
  <small><%= link_to "View", ticket_path(ticket) %>
  <%= link_to 'Destroy', ticket_path(ticket),
                    method: :delete, data: { confirm: 'Are you sure?' } %></small></h2>
  <table class="table"><p><%= ticket.body %></p></table>

   <td>

        <% if ticket.resolved? %>
          <%= button_to "Unresolved", ticket_path(ticket, ticket: {resolved: false}), class: "btn btn-primary", method: :patch %></td>
        <% else %>
          <%= button_to "Resolved", ticket_path(ticket, ticket: {resolved: true}), class: "btn btn-primary", method: :patch %>
        <% end %>

    </td>


  <hr>
<% end %>

<script>
$(function() {
  TicketsPage.initialize();
});
</script>

app/views/tickets/new.html.erb
<h1>New Post</h1>
<%= form_for Ticket.new do |f| %>
  <%= f.text_field :title %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>

app/views/tickets/show.html.erb
<!-- app/views/posts/show.html.erb -->
<p>
  <%= link_to "home", tickets_path %>
  <%= link_to "edit", edit_ticket_path(@ticket) %>
</p>
<h1><%= @ticket.title %></h1>
<p><%= @ticket.body %></p>
<p>Resolved: <%= @ticket.resolved %></p>